# Generated by Django 6.1 on 2026-08-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_target_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='target_minutes',
            field=models.IntegerField(default=3),
        ),
    ]
