# Generated by Django 6.1 on 2026-08-19 18:00
# target_minutes 기본값을 3 -> 5로 변경 (실제 허용 범위 5~30분과 안 맞았던 걸 수정)

from django.db import migrations, models


def fix_stale_default(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    # 옛 기본값(3분)이 그대로 남아있는, 즉 아직 실제로 시간을 설정한 적 없는 유저만 새 기본값으로 맞춘다
    User.objects.filter(target_minutes=3).update(target_minutes=5)


def revert_stale_default(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(target_minutes=5).update(target_minutes=3)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_target_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='target_minutes',
            field=models.IntegerField(default=5),
        ),
        migrations.RunPython(fix_stale_default, revert_stale_default),
    ]
