# Generated by Django 6.1 on 2026-08-12 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('guest_uuid', models.CharField(max_length=255, unique=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('total_minutes', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.JSONField(default=list)),
                ('preferred_type', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='onboarding.user')),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
    ]
