# Generated by Django 6.1 on 2026-08-13 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordContent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('content_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='records.record')),
            ],
            options={
                'db_table': 'record_contents',
                'ordering': ['sequence'],
            },
        ),
    ]
