# Generated by Django 6.1 on 2026-08-17 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_recordcontent'),
        ('teumteum', '0022_course_execution_satisfaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='teumteum.course'),
        ),
    ]
