# Generated by Django 6.1 on 2026-08-18 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_record_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='ai_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
