# Generated by Django 6.1 on 2026-08-18 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_alter_user_target_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WellnessArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='아티클 제목', max_length=200)),
                ('category', models.CharField(choices=[('스트레칭', '스트레칭'), ('건강', '건강'), ('마음', '마음'), ('영양', '영양'), ('피부', '피부'), ('수면', '수면')], help_text='표시 카테고리', max_length=20)),
                ('read_minutes', models.PositiveIntegerField(default=1, help_text='예상 소요 시간 (n분 읽기)')),
                ('image_url', models.URLField(blank=True, help_text='썸네일/상세 이미지 URL', max_length=500, null=True)),
                ('content', models.TextField(help_text='아티클/뉴스 본문 내용')),
                ('ai_summary', models.TextField(blank=True, help_text='AI 틈틈 한 줄 정리 (상세 화면 하단)', null=True)),
                ('target_wellness', models.JSONField(blank=True, default=list, help_text="온보딩 관심 웰니스 매칭 e.g., ['피부', '몸', '마음', '수면']")),
                ('target_content_types', models.JSONField(blank=True, default=list, help_text="온보딩 관심 콘텐츠/회복방식 매칭 e.g., ['독서', '듣기', '스트레칭', '마인드컨트롤']")),
                ('target_states', models.JSONField(blank=True, default=list, help_text="현재 상태 매칭 e.g., ['피곤해요', '긴장돼요', '복잡해요', '몸이 뻐근해요', '피부가 신경 쓰여요']")),
                ('target_places', models.JSONField(blank=True, default=list, help_text="현재 장소/틈 매칭 e.g., ['이동 중', '카페·실내', '학교·회사', '집', '약속 전', '휴식 중']")),
                ('target_schedules', models.JSONField(blank=True, default=list, help_text="다음 일정 매칭 e.g., ['수업·회의', '친구·약속', '업무·과제', '귀가·휴식']")),
                ('created_at', models.DateField(auto_now_add=True, help_text='등록일자')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '웰니스 아티클',
                'verbose_name_plural': '웰니스 아티클 목록',
                'db_table': 'wellness_articles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ArticleBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_articles', to='accounts.user')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='magazines.wellnessarticle')),
            ],
            options={
                'verbose_name': '아티클 북마크',
                'verbose_name_plural': '아티클 북마크 목록',
                'db_table': 'article_bookmarks',
                'unique_together': {('user', 'article')},
            },
        ),
    ]
