# Generated by Django 6.1 on 2026-08-13 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_user_target_minutes'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situation_option_id', models.IntegerField()),
                ('other_content', models.TextField(blank=True, null=True)),
                ('preferred_option_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_answers', to='accounts.user')),
            ],
            options={
                'db_table': 'main_answers',
            },
        ),
    ]
