# Generated by Django 6.1 on 2026-08-13 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.IntegerField(unique=True)),
                ('content', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'options',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.RemoveField(
            model_name='mainanswer',
            name='preferred_option_ids',
        ),
        migrations.RemoveField(
            model_name='mainanswer',
            name='situation_option_id',
        ),
        migrations.AddField(
            model_name='mainanswer',
            name='preferred_options',
            field=models.ManyToManyField(related_name='preferred_answers', to='teumteum.option'),
        ),
        migrations.AddField(
            model_name='mainanswer',
            name='situation_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='situation_answers', to='teumteum.option'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='teumteum.question'),
        ),
    ]
