# Generated by Django 6.1 on 2026-08-13 08:24

from django.db import migrations


def create_initial_questions(apps, schema_editor):
    Question = apps.get_model("teumteum", "Question")
    Option = apps.get_model("teumteum", "Option")

    # 첫 번째 질문
    q1 = Question.objects.create(
        question_id=1,
        title="현재 당신의 상황은?",
        description="상황에 맞추어 세션을 추천 드릴게요 :)"
    )

    # 두 번째 질문
    q2 = Question.objects.create(
        question_id=2,
        title="어떤 콘텐츠를 원하시나요?",
        description="알맞는 가이드로 추천 드릴게요 :)"
    )

    # 첫 번째 질문 선택지
    Option.objects.create(option_id=1, question=q1, content="길거리/대중교통")
    Option.objects.create(option_id=2, question=q1, content="카페/실내")
    Option.objects.create(option_id=3, question=q1, content="약속 직전")
    Option.objects.create(option_id=4, question=q1, content="기타")

    # 두 번째 질문 선택지
    Option.objects.create(option_id=5, question=q2, content="독서")
    Option.objects.create(option_id=6, question=q2, content="듣기")
    Option.objects.create(option_id=7, question=q2, content="스트레칭")
    Option.objects.create(option_id=8, question=q2, content="마인드컨트롤")


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0002_option_question_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_questions),
    ]
