# Generated by Django 6.1 on 2026-08-13 11:26

from django.db import migrations


def update_questions(apps, schema_editor):
    Question = apps.get_model("teumteum", "Question")
    Option = apps.get_model("teumteum", "Option")

    # 1번 질문 수정
    question1 = Question.objects.get(question_id=1)
    question1.description = "상황에 맞추어 세션을 추천 드릴게요 :) (단일 선택 가능)"
    question1.save()

    # 1번 질문 선택지 수정
    Option.objects.filter(question=question1, option_id=1).update(content="길거리")
    Option.objects.filter(question=question1, option_id=2).update(content="대중교통")
    Option.objects.filter(question=question1, option_id=3).update(content="카페")
    Option.objects.filter(question=question1, option_id=4).update(content="기타")

    # 2번 질문 수정
    question2 = Question.objects.get(question_id=2)
    question2.description = "알맞는 가이드로 추천 드릴게요 :) (복수 선택 가능)"
    question2.save()


class Migration(migrations.Migration):

    dependencies = [
        ("teumteum", "0003_initial_questions"),
    ]

    operations = [
        migrations.RunPython(update_questions),
    ]