# Generated by Django 6.1 on 2026-08-14 02:32

from django.db import migrations, models


def create_initial_time_setting(apps, schema_editor):
    TimeSetting = apps.get_model("teumteum", "TimeSetting")

    TimeSetting.objects.create(
        step=0,
        title="당신에게 남은 '틈'은?",
        description="최소 3분에서 최대 60분까지, 자유롭게 설정해요.",
        min_minutes=3,
        max_minutes=60
    )


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0004_update_question_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSetting',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True,
                    primary_key=True,
                    serialize=False,
                    verbose_name='ID'
                )),
                ('step', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('min_minutes', models.IntegerField()),
                ('max_minutes', models.IntegerField()),
            ],
            options={
                'db_table': 'time_settings',
            },
        ),
        migrations.RunPython(create_initial_time_setting),
    ]