# Generated by Django 6.1 on 2026-08-14 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_target_minutes'),
        ('teumteum', '0006_course_coursecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_minutes', models.IntegerField()),
                ('started_at', models.DateTimeField()),
                ('status', models.CharField(default='in_progress', max_length=30)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='teumteum.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_executions', to='accounts.user')),
            ],
            options={
                'db_table': 'course_executions',
            },
        ),
    ]
