# Generated by Django 6.1 on 2026-08-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0007_courseexecution'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
