# Generated by Django 6.1 on 2026-08-16 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_target_minutes'),
        ('teumteum', '0008_coursecontent_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('total_minutes', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_usages', to='accounts.user')),
            ],
            options={
                'db_table': 'weekly_usages',
                'constraints': [models.UniqueConstraint(fields=('user', 'week_start'), name='unique_user_week_usage')],
            },
        ),
    ]
