# Generated by Django 6.1 on 2026-08-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0009_weeklyusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseexecution',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
