# Generated by Django 6.1 on 2026-08-17
# 팀 원문 준비 전까지 쓸 플레이스홀더 웰니스 원문 시드 (실제 원문으로 교체 예정)

from django.db import migrations

ARTICLES = [
    {
        "title": "피로한 날 피부가 유난히 지쳐 보이는 이유",
        "topics": ["피부"],
        "content": (
            "잠이 부족하거나 피로가 쌓인 날에는 얼굴이 유난히 칙칙하고 푸석해 보인다. "
            "수면 부족은 피부 혈류를 줄여 안색을 어둡게 만들고, 스트레스 호르몬 분비를 늘려 "
            "피부 장벽을 약하게 만든다. 그 결과 평소보다 건조함과 예민함을 더 쉽게 느끼게 된다. "
            "이럴 때 새로운 제품을 더하기보다는, 지금 얼굴과 목에 들어간 긴장을 풀어주는 것이 "
            "먼저다. 턱과 미간에 힘이 들어가 있지는 않은지 확인하고, 물을 한 모금 마셔 "
            "몸에 수분을 보충하는 것만으로도 피부 컨디션에 도움이 된다. 짧은 틈에는 거창한 "
            "루틴보다, 지금 몸의 긴장을 알아차리고 풀어주는 것이 가장 효과적인 관리다."
        ),
    },
    {
        "title": "오래 앉아있으면 몸이 뻐근해지는 이유",
        "topics": ["몸"],
        "content": (
            "같은 자세로 오래 앉아있으면 목과 어깨 주변 근육이 지속적으로 긴장 상태에 놓인다. "
            "특히 화면을 오래 보면 고개가 앞으로 쏠리면서 목뒤 근육에 평소보다 훨씬 많은 "
            "부담이 실린다. 이 상태가 반복되면 뻐근함을 넘어 두통으로 이어지기도 한다. "
            "가장 좋은 방법은 짧게라도 자주 움직여주는 것이다. 어깨를 크게 으쓱했다가 "
            "천천히 내리거나, 고개를 좌우로 부드럽게 기울이는 것만으로도 뭉친 근육이 "
            "풀리기 시작한다. 하루 중 잠깐 생기는 틈은 몸이 보내는 신호를 알아차리고 "
            "가볍게 풀어줄 수 있는 좋은 기회다."
        ),
    },
    {
        "title": "머릿속이 복잡할 때 생각을 정리하는 법",
        "topics": ["마음"],
        "content": (
            "해야 할 일이 많거나 여러 생각이 동시에 떠오를 때는, 무엇부터 해결해야 할지 "
            "판단하기가 오히려 더 어려워진다. 머릿속으로만 정리하려 하면 같은 생각을 "
            "맴돌게 되는 경우가 많다. 이럴 때는 지금 떠오르는 생각 중 딱 하나만 짧게 "
            "적어보거나 소리 내어 말해보는 것이 도움이 된다. 생각을 밖으로 꺼내는 것만으로도 "
            "머릿속 공간이 정리되는 효과가 있다. 모든 걸 한 번에 해결하려 하지 않아도 "
            "괜찮다. 지금 당장 신경 쓰이는 것 한 가지만 짚어보는 것으로 충분하다."
        ),
    },
    {
        "title": "짧은 낮잠도 없이 버티는 오후, 무엇이 문제일까",
        "topics": ["몸", "마음"],
        "content": (
            "점심 이후 찾아오는 나른함은 대부분의 사람이 겪는 자연스러운 신체 리듬이다. "
            "이 시간대에 억지로 집중하려 하면 오히려 피로가 더 쌓이기 쉽다. 커피 한 잔에 "
            "의존하기보다, 잠깐 눈을 감고 호흡에 집중하거나 자리에서 일어나 몸을 가볍게 "
            "움직여주는 것이 회복에 더 효과적이다. 단 2~3분이라도 의식적으로 쉬어주는 "
            "시간을 가지면, 이후 남은 시간을 훨씬 가볍게 보낼 수 있다."
        ),
    },
    {
        "title": "잠들기 전 뒤척임이 길어지는 이유",
        "topics": ["수면"],
        "content": (
            "잠자리에 누웠는데도 쉽게 잠들지 못하는 날은, 하루 동안 쌓인 긴장이 몸에 "
            "그대로 남아있는 경우가 많다. 특히 잠들기 직전까지 화면을 보고 있으면 "
            "뇌가 각성 상태를 유지해 잠들기까지 더 오랜 시간이 걸린다. 잠들기 전에는 "
            "화면에서 눈을 떼고, 천천히 숨을 들이마시고 내쉬는 것에만 잠깐 집중해보는 "
            "것이 도움이 된다. 몸의 긴장이 풀리면 자연스럽게 잠도 따라온다."
        ),
    },
]


def create_wellness_article_sources(apps, schema_editor):
    WellnessArticleSource = apps.get_model("teumteum", "WellnessArticleSource")

    for article in ARTICLES:
        WellnessArticleSource.objects.create(
            title=article["title"],
            content=article["content"],
            topics=article["topics"],
        )


def remove_wellness_article_sources(apps, schema_editor):
    WellnessArticleSource = apps.get_model("teumteum", "WellnessArticleSource")
    WellnessArticleSource.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0020_wellness_article_source'),
    ]

    operations = [
        migrations.RunPython(
            create_wellness_article_sources,
            remove_wellness_article_sources,
        ),
    ]
