# Generated by Django 6.1 on 2026-08-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0021_seed_wellness_article_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseexecution',
            name='satisfaction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
