# Generated by Django 6.1 on 2026-08-17
# 코스 시간 범위를 3~60분에서 5~30분으로 변경

from django.db import migrations


def update_time_range(apps, schema_editor):
    TimeSetting = apps.get_model("teumteum", "TimeSetting")
    TimeSetting.objects.filter(step=0).update(min_minutes=5, max_minutes=30)


def revert_time_range(apps, schema_editor):
    TimeSetting = apps.get_model("teumteum", "TimeSetting")
    TimeSetting.objects.filter(step=0).update(min_minutes=3, max_minutes=60)


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0022_course_execution_satisfaction'),
    ]

    operations = [
        migrations.RunPython(update_time_range, revert_time_range),
    ]
