# Generated by Django 6.1 on 2026-08-17
# 체크인(skin_check) 유형을 쓰지 않기로 해서 시드 템플릿 제거

from django.db import migrations


def remove_skin_check_templates(apps, schema_editor):
    ActivityModuleTemplate = apps.get_model("teumteum", "ActivityModuleTemplate")
    ActivityModuleTemplate.objects.filter(content_type="skin_check").delete()


def restore_skin_check_template(apps, schema_editor):
    ActivityModuleTemplate = apps.get_model("teumteum", "ActivityModuleTemplate")
    ActivityModuleTemplate.objects.create(
        content_type="skin_check",
        title="오늘 피부 컨디션 체크",
        description="물 한 모금을 마시고, 턱에 들어간 힘을 30초 동안 천천히 내려놓아 보세요.",
        question="지금 피부 컨디션은 어떤가요?",
        question_options=["건조해요", "칙칙해요", "괜찮아요"],
        estimated_minutes=2,
        tags=["피부가 신경 쓰여요"],
        allowed_contexts=["이동 중", "카페·실내", "학교·회사", "집", "기타"],
    )


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0023_update_time_setting_range'),
    ]

    operations = [
        migrations.RunPython(
            remove_skin_check_templates,
            restore_skin_check_template,
        ),
    ]
