# Generated by Django 6.1 on 2026-08-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0024_remove_skin_check_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellnessarticlesource',
            name='source',
            field=models.CharField(default='틈틈 자체 작성', max_length=255),
        ),
    ]
