# Generated by Django 6.1 on 2026-08-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0027_seed_more_skin_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='current_state',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='place',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
