# Generated by Django 6.1 on 2026-08-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0028_course_current_state_course_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymoduletemplate',
            name='repeat_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='repeat_count',
            field=models.IntegerField(default=1),
        ),
    ]
