# Generated by Django 6.1 on 2026-08-17
# steps 합계와 estimated_minutes가 안 맞던 문제 수정: steps 세트를 반복하는 횟수(repeat_count)를 명시한다

from django.db import migrations

# {템플릿 제목: (steps 합계 초, repeat_count)}
REPEAT_COUNTS = {
    "2분 눈·호흡 리셋": 12,       # 10초(4+6) 호흡 사이클 x 12 = 120초
    "약속 전 긴장 리셋": 12,      # 10초(4+6) 호흡 사이클 x 12 = 120초
    "눈에 띄지 않는 목 리셋": 3,  # 60초(20+20+20) 스트레칭 세트 x 3 = 180초
}


def set_repeat_counts(apps, schema_editor):
    ActivityModuleTemplate = apps.get_model("teumteum", "ActivityModuleTemplate")

    for title, repeat_count in REPEAT_COUNTS.items():
        ActivityModuleTemplate.objects.filter(title=title).update(repeat_count=repeat_count)


def reset_repeat_counts(apps, schema_editor):
    ActivityModuleTemplate = apps.get_model("teumteum", "ActivityModuleTemplate")

    ActivityModuleTemplate.objects.filter(
        title__in=REPEAT_COUNTS.keys()
    ).update(repeat_count=1)


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0029_activitymoduletemplate_repeat_count_and_more'),
    ]

    operations = [
        migrations.RunPython(
            set_repeat_counts,
            reset_repeat_counts,
        ),
    ]
