# Generated by Django 6.1 on 2026-08-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0031_seed_more_activity_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=32, unique=True)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('estimated_minutes', models.IntegerField()),
                ('tags', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'youtube_video_sources',
            },
        ),
    ]
