# Generated by Django 6.1 on 2026-08-19
# 0023에서 min/max는 5~30분으로 바꿨는데 description 문구는 그대로 남아있던 걸 수정

from django.db import migrations


def update_description(apps, schema_editor):
    TimeSetting = apps.get_model("teumteum", "TimeSetting")
    TimeSetting.objects.filter(step=0).update(
        description="최소 5분에서 최대 30분까지, 자유롭게 설정해요."
    )


def revert_description(apps, schema_editor):
    TimeSetting = apps.get_model("teumteum", "TimeSetting")
    TimeSetting.objects.filter(step=0).update(
        description="최소 3분에서 최대 60분까지, 자유롭게 설정해요."
    )


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0034_lengthen_url_based_articles'),
    ]

    operations = [
        migrations.RunPython(update_description, revert_description),
    ]
