# Generated by Django 6.1 on 2026-08-19
# 유튜브 더미 풀에 8개 추가 시드

from django.db import migrations

ENTRIES = [
    {
        "video_id": 'ntsiwrBkRHs',
        "url": "https://www.youtube.com/watch?v=ntsiwrBkRHs",
        "title": '따라하면 무조건 피부 좋아지는 한혜진 관리법 (주름,탄력,꿀팁,스킨케어루틴)',
        "channel_name": '한혜진 Han Hye Jin',
        "thumbnail_url": 'https://i.ytimg.com/vi/ntsiwrBkRHs/mqdefault.jpg',
        "estimated_minutes": 12,
        "tags": ["스트레칭"],
    },
    # '-qDo0LIdiPw'는 기존 50개 더미풀에 이미 있던 영상이라 제외함
    {
        "video_id": 'po3MAd6bOUg',
        "url": "https://www.youtube.com/watch?v=po3MAd6bOUg",
        "title": '청담 피부 클리닉 의사가 추천하는 인생 리프팅 딱 하나',
        "channel_name": '엠레드 클리닉 AMRED CLINIC',
        "thumbnail_url": 'https://i.ytimg.com/vi/po3MAd6bOUg/mqdefault.jpg',
        "estimated_minutes": 8,
        "tags": ["스트레칭"],
    },
    {
        "video_id": 'Fsdy_dmUgBY',
        "url": "https://www.youtube.com/watch?v=Fsdy_dmUgBY",
        "title": '승모근 통증까지 없애주는 완벽 스트레칭 I 운동치료사가 알려주는 자세',
        "channel_name": '엠레드 클리닉 AMRED CLINIC',
        "thumbnail_url": 'https://i.ytimg.com/vi/Fsdy_dmUgBY/mqdefault.jpg',
        "estimated_minutes": 7,
        "tags": ["스트레칭"],
    },
    {
        "video_id": 'K7yWfpUl2dI',
        "url": "https://www.youtube.com/watch?v=K7yWfpUl2dI",
        "title": '피부과 원장이 10년째 하는 얼굴 붓기 빼는 법',
        "channel_name": '의사결정',
        "thumbnail_url": 'https://i.ytimg.com/vi/K7yWfpUl2dI/mqdefault.jpg',
        "estimated_minutes": 7,
        "tags": ["스트레칭"],
    },
    {
        "video_id": 'zwyE03MnsEs',
        "url": "https://www.youtube.com/watch?v=zwyE03MnsEs",
        "title": "피부를 지키기 위해 꼭 봐야하는 '선크림' 제대로 바르는 꿀팁",
        "channel_name": '엠레드 클리닉 AMRED CLINIC',
        "thumbnail_url": 'https://i.ytimg.com/vi/zwyE03MnsEs/mqdefault.jpg',
        "estimated_minutes": 6,
        "tags": ["스트레칭"],
    },
    {
        "video_id": 'LyxSZg9tydc',
        "url": "https://www.youtube.com/watch?v=LyxSZg9tydc",
        "title": '광고❌피부과 의사가 자기 돈 10만원으로 올리브영 스킨 케어를 산다면?',
        "channel_name": '스튜디오 엠레드 Studio Amred',
        "thumbnail_url": 'https://i.ytimg.com/vi/LyxSZg9tydc/mqdefault.jpg',
        "estimated_minutes": 13,
        "tags": ["스트레칭"],
    },
    {
        "video_id": 'UeUi_BXcwMs',
        "url": "https://www.youtube.com/watch?v=UeUi_BXcwMs",
        "title": '종아리 얇아지는 마법의 스트레칭 I 운동치료사가 알려주는 자세',
        "channel_name": '엠레드 클리닉 AMRED CLINIC',
        "thumbnail_url": 'https://i.ytimg.com/vi/UeUi_BXcwMs/mqdefault.jpg',
        "estimated_minutes": 9,
        "tags": ["스트레칭"],
    },
]


def create_youtube_video_sources(apps, schema_editor):
    YoutubeVideoSource = apps.get_model("teumteum", "YoutubeVideoSource")

    for entry in ENTRIES:
        YoutubeVideoSource.objects.create(**entry)


def remove_youtube_video_sources(apps, schema_editor):
    YoutubeVideoSource = apps.get_model("teumteum", "YoutubeVideoSource")
    video_ids = [entry["video_id"] for entry in ENTRIES]
    YoutubeVideoSource.objects.filter(video_id__in=video_ids).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0035_fix_time_setting_description'),
    ]

    operations = [
        migrations.RunPython(
            create_youtube_video_sources,
            remove_youtube_video_sources,
        ),
    ]
