# Generated by Django 6.1 on 2026-08-19
# 마음정리 활동모듈 정리:
# - id=4: steps가 비어있는(질문이 하나도 안 뜨는) 오래된 데이터라 비활성화
# - id=26, 27: 실제로는 "다음 일정" 답변과 무관하게 뽑히는데 제목/문구에
#   특정 시나리오(친구·약속, 다음 수업)가 박혀있어서 마치 그 답변을 반영한 것처럼
#   보이던 문제 -> 상황 무관한 문구로 순화

from django.db import migrations


def fix_templates(apps, schema_editor):
    ActivityModuleTemplate = apps.get_model("teumteum", "ActivityModuleTemplate")

    ActivityModuleTemplate.objects.filter(id=4).update(is_active=False)

    ActivityModuleTemplate.objects.filter(id=26).update(
        title="3분 마음 정리",
    )

    template_27 = ActivityModuleTemplate.objects.filter(id=27).first()
    if template_27:
        template_27.title = "3분 생각 정리"
        template_27.steps = [
            {
                "order": 1,
                "question": "지금 머릿속에 가장 많이 남아 있는 생각은 무엇인가요?",
                "duration_seconds": 60,
                "type": "optional_text",
                "options": [],
            },
            {
                "order": 2,
                "question": "다음 할 일에서 한 가지에만 집중한다면 무엇인가요?",
                "duration_seconds": 60,
                "type": "optional_text",
                "options": [],
            },
            {
                "order": 3,
                "question": "다음 일정이 시작되면 가장 먼저 할 행동은 무엇인가요?",
                "duration_seconds": 60,
                "type": "optional_text",
                "options": [],
            },
        ]
        template_27.save()


def revert_templates(apps, schema_editor):
    ActivityModuleTemplate = apps.get_model("teumteum", "ActivityModuleTemplate")

    ActivityModuleTemplate.objects.filter(id=4).update(is_active=True)
    ActivityModuleTemplate.objects.filter(id=26).update(
        title="3분 친구를 만나기 전 마음 정리",
    )

    template_27 = ActivityModuleTemplate.objects.filter(id=27).first()
    if template_27:
        template_27.title = "3분 다음 수업 준비"
        template_27.steps = [
            {
                "order": 1,
                "question": "지금 머릿속에 가장 많이 남아 있는 생각은 무엇인가요?",
                "duration_seconds": 60,
                "type": "optional_text",
                "options": [],
            },
            {
                "order": 2,
                "question": "다음 수업에서 한 가지에만 집중한다면 무엇인가요?",
                "duration_seconds": 60,
                "type": "optional_text",
                "options": [],
            },
            {
                "order": 3,
                "question": "수업이 시작되면 가장 먼저 할 행동은 무엇인가요?",
                "duration_seconds": 60,
                "type": "optional_text",
                "options": [],
            },
        ]
        template_27.save()


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0036_seed_more_youtube_video_sources'),
    ]

    operations = [
        migrations.RunPython(fix_templates, revert_templates),
    ]
