# Generated by Django 6.1 on 2026-08-19 23:16
# total_seconds/target_seconds 새 필드 추가 후, 기존에 이미 만들어져 있던
# 코스/실행 기록들은 정확한 초 단위 값을 알 수 없으니 분 단위 값 * 60으로 채워둔다
# (없는 것보다는 낫고, 실행 재시작 시 타이머가 0으로 깨지는 것도 막아준다).

from django.db import migrations, models


def backfill_seconds(apps, schema_editor):
    Course = apps.get_model("teumteum", "Course")
    CourseExecution = apps.get_model("teumteum", "CourseExecution")

    for course in Course.objects.filter(total_seconds=0):
        course.total_seconds = course.total_minutes * 60
        course.save(update_fields=["total_seconds"])

    for execution in CourseExecution.objects.filter(target_seconds=0):
        execution.target_seconds = execution.target_minutes * 60
        execution.save(update_fields=["target_seconds"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0037_fix_reflection_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='total_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='courseexecution',
            name='target_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(backfill_seconds, noop),
    ]
