# Generated by Django 6.1 on 2026-08-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0038_course_total_seconds_courseexecution_target_seconds'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideosource',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
