# Generated by Django 6.1 on 2026-08-20
# 더미풀 유튜브 57개의 실제 초 단위 길이를 유튜브 API로 조회해서 채워 넣는다.
# (더미풀 영상이 뽑혀도 코스 총 시간을 분 단위 반올림이 아니라 초 단위로 정밀하게 계산할 수 있게)

from django.db import migrations

DURATIONS = {'-qDo0LIdiPw': 520, '0mCDq0f4sfI': 198, '2j9SRYlolfQ': 249, '5RSNkk2jNzk': 571, '6_LYz_XxD-g': 556, '9PXvN8Iw7ns': 168, 'AEbr_-Z86tU': 264, 'AcLocBgzn0Y': 172, 'BmEt-d-dw58': 401, 'Ca08SKIk8ds': 334, 'F-Jd4kI6rdM': 684, 'FMOISIlhLEY': 543, 'Fsdy_dmUgBY': 414, 'I0Hi6xOjzdI': 717, 'I6eS-XxmVEU': 296, 'JsF2nzetLBU': 650, 'K7yWfpUl2dI': 389, 'Kl9Dmx86Z0Q': 189, 'LyxSZg9tydc': 776, 'MRKgRMB5VSw': 379, 'OKyuFF3uh5o': 345, 'OQraCI5VZuA': 299, 'P0jZYGRoafI': 192, 'PoYzxj8Iy5M': 164, 'QAKh9isHbLE': 426, 'T-bVqdhqW2U': 935, 'TDmqXm6ZkKw': 504, 'TzIEqLmK_4c': 481, 'UAsiJxiaqRQ': 131, 'UeUi_BXcwMs': 502, 'Uf5tcB2BmVw': 780, 'Ur-E2QnXON4': 308, 'VOdU5hn0MZw': 266, 'ZDYTOVkItLs': 341, 'ZFEj0cWxw08': 470, 'ZHQ5CHKSQvs': 390, '_m4ZbflEEhc': 384, 'awNAKRWO5-Y': 131, 'cl5cc1_5zZc': 380, 'dJXZRZvqbYg': 354, 'dZbPtAgofwI': 250, 'gxGd1t8jh98': 479, 'h7cZIEcqB10': 374, 'jo0I3xTGaVU': 335, 'jxf_3r8xFa4': 165, 'kgCj8UUEWjU': 647, 'lQxqPnjsB0I': 629, 'ntsiwrBkRHs': 710, 'po3MAd6bOUg': 445, 'qquOD3zklOk': 401, 'sIb98vf3u_w': 989, 'ut_Lc_iz-As': 459, 'wEw1AOFpJPc': 373, 'xhIFllbqCKU': 427, 'xw45QeWoUhQ': 263, 'yz1nWxCB3-4': 293, 'zwyE03MnsEs': 325}


def backfill_durations(apps, schema_editor):
    YoutubeVideoSource = apps.get_model("teumteum", "YoutubeVideoSource")
    for video_id, seconds in DURATIONS.items():
        YoutubeVideoSource.objects.filter(video_id=video_id).update(duration_seconds=seconds)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0039_youtubevideosource_duration_seconds'),
    ]

    operations = [
        migrations.RunPython(backfill_durations, noop),
    ]
