# Generated by Django 6.1 on 2026-08-20 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0040_seed_dummy_pool_durations'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitymoduletemplate',
            name='target_schedules',
            field=models.JSONField(default=list),
        ),
    ]
