# Generated by Django 6.1 on 2026-08-20
# 마음정리 회복방식 + 다음 일정 답변별로 정확히 맞는 고정 문구 reflection 템플릿 4개 추가.
# AI 생성이 아니라 고정 데이터라 OpenAI 한도랑 무관하게 항상 정상 동작한다.
# target_schedules가 있는 템플릿은 실제 다음 일정 답변과 정확히 일치할 때만 후보에 들어가고
# (services/course.py의 select_activity_module 참고), "없음"/"기타"거나 안 맞으면
# 자동으로 기존 범용 마음정리 템플릿들 중에서 골라진다.

from django.db import migrations

ENTRIES = [
    {
        "content_type": "reflection",
        "title": "수업회의 전, 마음정리",
        "description": "정답은 없어요. 지금 떠오르는 만큼만 생각해보세요.",
        "question": "오늘 이 수업 또는 회의에서 내가 미리 정리해두고 싶은 생각은 무엇인가요?",
        "question_options": [],
        "allow_text_input": True,
        "estimated_minutes": 2,
        "tags": [],
        "allowed_contexts": [],
        "target_schedules": ["수업·회의"],
    },
    {
        "content_type": "reflection",
        "title": "친구를 만나기 전, 마음 정리",
        "description": "정답은 없어요. 지금 떠오르는 만큼만 생각해보세요.",
        "question": "오늘 이 약속에서 내가 가장 기대하는 순간은 무엇인가요?",
        "question_options": [],
        "allow_text_input": True,
        "estimated_minutes": 2,
        "tags": [],
        "allowed_contexts": [],
        "target_schedules": ["친구·약속"],
    },
    {
        "content_type": "reflection",
        "title": "업무 또는 과제 전, 마음정리",
        "description": "정답은 없어요. 지금 떠오르는 만큼만 생각해보세요.",
        "question": "오늘 이 업무 또는 과제에서 내가 가장 신경써야하는 부분은 무엇인가요?",
        "question_options": [],
        "allow_text_input": True,
        "estimated_minutes": 2,
        "tags": [],
        "allowed_contexts": [],
        "target_schedules": ["업무·과제"],
    },
    {
        "content_type": "reflection",
        "title": "귀가 또는 휴식 전, 마음정리",
        "description": "정답은 없어요. 지금 떠오르는 만큼만 생각해보세요.",
        "question": "오늘 하루, 나에게 가장 수고했다고 말해주고 싶은 순간은 언제인가요?",
        "question_options": [],
        "allow_text_input": True,
        "estimated_minutes": 2,
        "tags": [],
        "allowed_contexts": [],
        "target_schedules": ["귀가·휴식"],
    },
]


def seed_templates(apps, schema_editor):
    ActivityModuleTemplate = apps.get_model("teumteum", "ActivityModuleTemplate")
    for entry in ENTRIES:
        ActivityModuleTemplate.objects.create(**entry)


def remove_templates(apps, schema_editor):
    ActivityModuleTemplate = apps.get_model("teumteum", "ActivityModuleTemplate")
    titles = [entry["title"] for entry in ENTRIES]
    ActivityModuleTemplate.objects.filter(title__in=titles).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0041_activitymoduletemplate_target_schedules'),
    ]

    operations = [
        migrations.RunPython(seed_templates, remove_templates),
    ]
