# Generated by Django 6.1 on 2026-08-20
# "수업회의" -> "수업 또는 회의"로 문구 통일 (업무 또는 과제 등 다른 문구랑 표기 맞춤)

from django.db import migrations


def fix_title(apps, schema_editor):
    ActivityModuleTemplate = apps.get_model("teumteum", "ActivityModuleTemplate")
    ActivityModuleTemplate.objects.filter(title="수업회의 전, 마음정리").update(
        title="수업 또는 회의 전, 마음정리"
    )


def revert_title(apps, schema_editor):
    ActivityModuleTemplate = apps.get_model("teumteum", "ActivityModuleTemplate")
    ActivityModuleTemplate.objects.filter(title="수업 또는 회의 전, 마음정리").update(
        title="수업회의 전, 마음정리"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0042_seed_schedule_specific_reflection'),
    ]

    operations = [
        migrations.RunPython(fix_title, revert_title),
    ]
