# Generated by Django 6.1 on 2026-08-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0043_fix_class_meeting_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseexecution',
            name='skipped_count',
            field=models.IntegerField(default=0),
        ),
    ]
