# Generated by Django 6.1 on 2026-08-20 15:51
# 기존 콘텐츠들은 정밀한 초 단위 값이 없으니 estimated_minutes*60으로 채워둔다
# (없는 것보다 낫고, 유튜브처럼 원래 정밀했던 값은 몰라도 최소한 0으로 비진 않게 함)

from django.db import migrations, models


def backfill_duration_seconds(apps, schema_editor):
    CourseContent = apps.get_model("teumteum", "CourseContent")
    for content in CourseContent.objects.filter(duration_seconds=0):
        content.duration_seconds = content.estimated_minutes * 60
        content.save(update_fields=["duration_seconds"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0044_courseexecution_skipped_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursecontent',
            name='duration_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.RunPython(backfill_duration_seconds, noop),
    ]
