# Generated by Django 6.1 on 2026-08-20 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_target_minutes'),
        ('teumteum', '0045_coursecontent_duration_seconds'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=32)),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('estimated_minutes', models.IntegerField()),
                ('duration_seconds', models.IntegerField(default=0)),
                ('tags', models.JSONField(default=list)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_videos', to='accounts.user')),
            ],
            options={
                'db_table': 'shared_videos',
                'unique_together': {('user', 'video_id')},
            },
        ),
    ]
