# Generated by Django 6.1 on 2026-08-20 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teumteum', '0046_sharedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
